labels:
  environment: production
  framework: mysql
  repo: https://github.com/iamkhaya/tml-mysql
  task: service
  team: tml-backend
replicas: 1
env:
  role: PRODUCTION
image:
  repository: eu.gcr.io/thumela-265921
  tag: master
  pullPolicy: Always
ports:
  containerPort: 3306
