labels:
  environment: staging
  framework: mysql
  repo: https://github.com/iamkhaya/tml-mysql
  task: service
  team: tml-backend
replicas: 1
env:
  role: DEV
image:
  repository: registry.digitalocean.com/tml-container-registry
  tag: master
  pullPolicy: IfNotPresent
ports:
  containerPort: 3306
